### ISSUE TITLE
paralleltest cause a panic

### ISSUE THREAD

**Issue by SuperHiroki** [kunwardeep/paralleltest#37]
I created a minimal test case to reproduce the bug.

### (2) I created Go environment by referring to the [official site](https://go.dev/doc/install) .
```jsx
sudo chmod 777 -R /usr/local
```
I downloaded “go1.23.1.linux-amd64.tar.gz”  and place it under “/usr/local” .
```jsx
rm -rf /usr/local/go && tar -C /usr/local -xzf go1.23.1.linux-amd64.tar.gz
```
```jsx
echo 'export PATH=$PATH:/usr/local/go/bin' >> ~/.bashrc
echo 'export GOPATH=$HOME/go' >> ~/.bashrc
echo 'export PATH=$PATH:$GOPATH/bin' >> ~/.bashrc
source ~/.bashrc
echo $PATH
go version
```

### (3) I made go files.
```jsx
cd ~
~$ mkdir MyTry
~$ cd MyTry
~/MyTry$ sudo nano double.go
package main

func Double(x int) int {
    return x * 2
}

~/MyTry$ sudo nano double_test.go
package main

import (
    "testing"
    "github.com/stretchr/testify/assert"
)

func TestDouble(t *testing.T) {
		t.Parallel()  

    result := Double(2)
    assert.Equal(t, 4, result, "Double(2) should be 4")
}
```

### (4) I confirmed that other tools work fine.
```jsx
~/MyTry$ go mod init mytry
~/MyTry$ go mod tidy
~/MyTry$ go test ./...
ok      mytry   0.002s
~/MyTry$ go install honnef.co/go/tools/cmd/staticcheck@latest
~/MyTry$ ls -l ~/go/bin
~/MyTry$ staticcheck ./...
```

### (5) When starting paralleltest, I got a panic.
```jsx
~/MyTry$ go install github.com/kunwardeep/paralleltest@latest
~/MyTry$ ls -l ~/go/bin
~/MyTry$ paralleltest ./...
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x59b32f]

goroutine 8 [running]:
go/types.(*Checker).handleBailout(0xc00014a1c0, 0xc0000d3bf0)
        /usr/local/go/src/go/types/check.go:404 +0x88
panic({0x7288a0?, 0x9bfaa0?})
        /usr/local/go/src/runtime/panic.go:785 +0x132
go/types.(*StdSizes).Sizeof(0x0, {0x7f69d0, 0x9c3880})
        /usr/local/go/src/go/types/sizes.go:229 +0x30f
go/types.(*Config).sizeof(...)
        /usr/local/go/src/go/types/sizes.go:334
go/types.representableConst.func1({0x7f69d0?, 0x9c3880?})
        /usr/local/go/src/go/types/const.go:77 +0x86
go/types.representableConst({0x7f81c8, 0x9b8430}, 0xc00014a1c0, 0x9c3880, 0xc0000d2960)
        /usr/local/go/src/go/types/const.go:93 +0x173
go/types.(*Checker).representation(0xc00014a1c0, 0xc0000a7840, 0x9c3880)
        /usr/local/go/src/go/types/const.go:257 +0x65
go/types.(*Checker).implicitTypeAndValue(0xc00014a1c0, 0xc0000a7840, {0x7f69d0, 0x9c3880})
        /usr/local/go/src/go/types/expr.go:377 +0x2d7
go/types.(*Checker).convertUntyped(0xc00014a1c0, 0xc0000a7840, {0x7f69d0, 0x9c3880})
        /usr/local/go/src/go/types/const.go:290 +0x3f
go/types.(*Checker).matchTypes(0xc00014a1c0, 0xc0000a7800, 0xc0000a7840)
        /usr/local/go/src/go/types/expr.go:928 +0x79
go/types.(*Checker).binary(0xc00014a1c0, 0xc0000a7800, {0x7f7898, 0xc00008bb00}, {0x7f7418, 0xc0000ac840}, {0x7f7d78, 0xc0000ac860}, 0xe, 0x35)
        /usr/local/go/src/go/types/expr.go:802 +0x166
go/types.(*Checker).exprInternal(0xc00014a1c0, 0x0, 0xc0000a7800, {0x7f7898, 0xc00008bb00}, {0x0, 0x0})
        /usr/local/go/src/go/types/expr.go:1452 +0x206
go/types.(*Checker).rawExpr(0xc00014a1c0, 0x0, 0xc0000a7800, {0x7f7898?, 0xc00008bb00?}, {0x0?, 0x0?}, 0x0)
        /usr/local/go/src/go/types/expr.go:981 +0x18c
go/types.(*Checker).expr(0xc00014a1c0, 0x9c3880?, 0xc0000a7800, {0x7f7898?, 0xc00008bb00?})
        /usr/local/go/src/go/types/expr.go:1549 +0x30
go/types.(*Checker).initVars(0xc00014a1c0, {0xc000094598, 0x1, 0x0?}, {0xc0000932b0, 0x77b936?, 0x3?}, {0x7f7b38, 0xc0000ac880})
        /usr/local/go/src/go/types/assignments.go:398 +0x60b
go/types.(*Checker).stmt(0xc00014a1c0, 0x0, {0x7f7b38, 0xc0000ac880})
        /usr/local/go/src/go/types/stmt.go:533 +0x1777
go/types.(*Checker).stmtList(0xc00014a1c0, 0x0, {0xc0000932c0?, 0x565bc0?, 0xc00014a1c0?})
        /usr/local/go/src/go/types/stmt.go:121 +0x85
go/types.(*Checker).funcBody(0xc00014a1c0, 0x7f7418?, {0xc000090a18?, 0x0?}, 0xc0000a7700, 0xc00008bb30, {0x0?, 0x0?})
        /usr/local/go/src/go/types/stmt.go:41 +0x2f3
go/types.(*Checker).funcDecl.func1()
        /usr/local/go/src/go/types/decl.go:888 +0x3a
go/types.(*Checker).processDelayed(0xc00014a1c0, 0x0)
        /usr/local/go/src/go/types/check.go:516 +0x15c
go/types.(*Checker).checkFiles(0xc00014a1c0, {0xc000094530, 0x1, 0x1})
        /usr/local/go/src/go/types/check.go:462 +0x17e
go/types.(*Checker).Files(0xc0001020e0?, {0xc000094530?, 0xc0000a8de0?, 0x6?})
        /usr/local/go/src/go/types/check.go:422 +0x75
golang.org/x/tools/go/packages.(*loader).loadPackage(0xc0001020e0, 0xc00039a240)
        /home/ubuntu/go/pkg/mod/golang.org/x/tools@v0.7.0/go/packages/packages.go:1052 +0xa32
golang.org/x/tools/go/packages.(*loader).loadRecursive.func1()
        /home/ubuntu/go/pkg/mod/golang.org/x/tools@v0.7.0/go/packages/packages.go:851 +0x1a9
sync.(*Once).doSlow(0xc000046798?, 0x405997?)
        /usr/local/go/src/sync/once.go:76 +0xb4
sync.(*Once).Do(...)
        /usr/local/go/src/sync/once.go:67
golang.org/x/tools/go/packages.(*loader).loadRecursive(0x66cf3e?, 0xc0000467d0?)
        /home/ubuntu/go/pkg/mod/golang.org/x/tools@v0.7.0/go/packages/packages.go:839 +0x3b
golang.org/x/tools/go/packages.(*loader).refine.func2(0x0?)
        /home/ubuntu/go/pkg/mod/golang.org/x/tools@v0.7.0/go/packages/packages.go:774 +0x26
created by golang.org/x/tools/go/packages.(*loader).refine in goroutine 1
        /home/ubuntu/go/pkg/mod/golang.org/x/tools@v0.7.0/go/packages/packages.go:773 +0xcaf
```

**Comment by kunwardeep** [comment]
hey @SuperHiroki are you able to test this again with the latest version?

**Comment by kunwardeep** [comment]
Closing it for now, as there is no follow-up
